# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities

import auth_pb2 as auth__pb2


class AuthServiceStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetToken = channel.unary_unary(
        '/AuthService/GetToken',
        request_serializer=auth__pb2.LoginData.SerializeToString,
        response_deserializer=auth__pb2.LoginResponse.FromString,
        )
    self.InvalidateToken = channel.unary_unary(
        '/AuthService/InvalidateToken',
        request_serializer=auth__pb2.Token.SerializeToString,
        response_deserializer=auth__pb2.Empty.FromString,
        )
    self.GetPermissions = channel.unary_unary(
        '/AuthService/GetPermissions',
        request_serializer=auth__pb2.Token.SerializeToString,
        response_deserializer=auth__pb2.Permissions.FromString,
        )
    self.GetUserId = channel.unary_unary(
        '/AuthService/GetUserId',
        request_serializer=auth__pb2.Token.SerializeToString,
        response_deserializer=auth__pb2.UserId.FromString,
        )


class AuthServiceServicer(object):

  def GetToken(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def InvalidateToken(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPermissions(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUserId(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetToken': grpc.unary_unary_rpc_method_handler(
          servicer.GetToken,
          request_deserializer=auth__pb2.LoginData.FromString,
          response_serializer=auth__pb2.LoginResponse.SerializeToString,
      ),
      'InvalidateToken': grpc.unary_unary_rpc_method_handler(
          servicer.InvalidateToken,
          request_deserializer=auth__pb2.Token.FromString,
          response_serializer=auth__pb2.Empty.SerializeToString,
      ),
      'GetPermissions': grpc.unary_unary_rpc_method_handler(
          servicer.GetPermissions,
          request_deserializer=auth__pb2.Token.FromString,
          response_serializer=auth__pb2.Permissions.SerializeToString,
      ),
      'GetUserId': grpc.unary_unary_rpc_method_handler(
          servicer.GetUserId,
          request_deserializer=auth__pb2.Token.FromString,
          response_serializer=auth__pb2.UserId.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'AuthService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
