import { Message } from '../message'

export const MESSAGES: Message[] = [
	{id: 1, from: 'John Doe', date: '2017-01-01', topic: 'Re: Ważne!', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum '},
	{id: 2, from: 'John Doe', date: '2017-01-01', topic: 'Re: Ważne!', content: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that produces no resultant pleasure?'},
	{id: 3, from: 'John Mock', date: '2017-01-01', topic: 'Re: Ważne!', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum '},
	{id: 4, from: 'John Doe', date: '2017-01-01', topic: 'Re: Ważne!', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum '},
	{id: 5, from: 'John Doe', date: '2017-01-01', topic: 'Re: Ważne!', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum '},
	{id: 6, from: 'John Doe', date: '2017-01-01', topic: 'Re: Ważne!', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum '},
	{id: 7, from: 'Adam Małysz', date: '2017-01-01', topic: 'Gratuluję rekordu w Planicy!', content: 'Gdy mamy młodego chłopaka, który pierwszy raz przyjeżdża na skocznię mamucią, to jego pierwsze dwa, trzy skoki to takie próby na rozpoznanie. Nikt mi ze skoczków nie powie, że się w ogóle nie boi. Niestety, to jest sport, gdzie nie wszystko zależy od zawodnika. Może być nagły wiatr z boku, może mu narty porwać. Jak siedziałem na belce albo zbliżałem się do niej i nagle widziałem, że zawodnik kręci jakieś dziwne piruety w powietrzu, na pewno byłem zaszokowany. Ale skoki to automatyzm, odruchy. I proszę mi wierzyć – trzeba by bardzo dużo myśleć o tym, co stało się wcześniej, żeby zrobić tak samo'},
];