# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('pesel', models.CharField(max_length=11)),
                ('data_urodzenia', models.CharField(max_length=10)),
                ('nip', models.CharField(max_length=100)),
                ('miejscowosc', models.CharField(max_length=100)),
                ('kod_pocztowy', models.CharField(max_length=6)),
                ('ulica', models.CharField(max_length=200)),
                ('nr_domu', models.CharField(max_length=20)),
                ('nr_mieszkania', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Zwolnienie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poczatek', models.CharField(max_length=50)),
                ('koniec', models.CharField(max_length=50)),
                ('icd', models.CharField(max_length=50)),
                ('opis', models.CharField(max_length=250)),
                ('osoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zwolnienia.Osoba')),
            ],
        ),
    ]
