# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wnioski', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wniosek',
            name='status',
            field=models.CharField(choices=[('0', 'oczekuje'), ('1', 'pozytywny'), ('2', 'negatywny')], default='1', max_length=1),
        ),
    ]
