# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wnioski', '0002_wniosek_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='czlonekrodziny',
            name='imie',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='czlonekrodziny',
            name='nazwisko',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='czlonekrodziny',
            name='pesel',
            field=models.CharField(default='a', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wniosek',
            name='dodano',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wniosek',
            name='status',
            field=models.CharField(choices=[('0', 'oczekuje'), ('1', 'pozytywny'), ('2', 'negatywny')], default='0', max_length=1),
        ),
    ]
