# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wnioski', '0003_auto_20170517_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='wniosek',
            name='niepelnosprawne',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
